### ISSUE TITLE
loader/service: service name is likely to conflict

### ISSUE THREAD

**Issue by DuanPengfei** [akyuujs/akyuu#17]
Version: 0.2.0
Platform: macOS
Subsystem: loader/service

The loader/service use the filename as the service name. But if there exist same name file in the secondary folder of services, the two same name service will conflict.

**Comment by XadillaX** [comment]
Landed in https://github.com/akyuujs/akyuu/commit/c232d6184147d961f4b94172e5ce9bd27e742654
