### ISSUE TITLE
运行 example 报错

### ISSUE THREAD

**Issue by xiaoqiangsdl** [akyuujs/akyuu#26]
* **Version**: 0.3.0
* **Node.js Version**: 8.1.2
* **Platform**: Darwin codesword.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
* **Subsystem**: example

进入路由 jiandan 时报错

报错信息：
No such service jiandan

**Comment by XadillaX** [comment]
Refs: https://github.com/akyuujs/akyuu/pull/18

Would you please fix this bug on example?
