### ISSUE TITLE
Add a style guide

### ISSUE THREAD

**Issue by anshumanv** [akyuujs/akyuu#32]
Style guide ensures that the contributors stick to the coding guidelines and thus improves the code quality.

I've personally used XO since it's easy to use.

**Comment by XadillaX** [comment]
Thx, but what do you mean about XO?

**Comment by anshumanv** [comment]
It is a js linting tool based on ESLint : https://github.com/sindresorhus/xo

**Comment by XadillaX** [comment]
Currently we have ESLint in the project and IMHO I think it will last a period of time.

**Comment by anshumanv** [comment]
I think we should migrate to xo because of its simplicity, what are your views on this @XadillaX ?

**Comment by DuanPengfei** [comment]
After learning about XO, I personally felt that there was no reason to migrate. ESLint is very widely used, and it is easy to find a solution when you encounter problems. XO introduced that is happiness style linter, but there is no strong contrast with the way ESLint use. Maybe I have not encountered the pain of using ESLint, so I feeling no need to migrate.

**Comment by anshumanv** [comment]
Alright then, let's continue using ESLint then. 👍
